// packages/vue/src/BrandMark.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  buildRootStyle,
  markViewBox,
  renderMarkChildren,
  type BrandMarkSharedProps,
} from '@kolektiv/brand-core';

defineOptions({ name: 'BrandMark', inheritAttrs: false });

const props = defineProps<BrandMarkSharedProps>();

const rootStyle = computed(() =>
  buildRootStyle({
    colors: props.colors,
    color: props.color,
    style: props.style,
  }),
);

const inner = computed(() =>
  renderMarkChildren({ parts: props.parts, variant: props.variant, title: props.title }),
);
</script>

<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    :viewBox="markViewBox"
    fill="none"
    width="100%"
    :style="rootStyle"
    :role="title ? 'img' : undefined"
    :aria-label="title || undefined"
    :aria-hidden="title ? undefined : true"
    v-bind="$attrs"
    v-html="inner"
  />
</template>

// packages/svelte/src/lib/BrandMark.svelte
<script lang="ts">
  import {
    buildRootStyle,
    markViewBox,
    renderMarkChildren,
    styleToCssText,
    type BrandMarkSharedProps,
  } from '@kolektiv/brand-core';

  type BrandMarkProps = BrandMarkSharedProps & {
    class?: string;
    [key: string]: unknown;
  };

  let {
    colors,
    parts,
    variant,
    color,
    title,
    class: className = '',
    style,
    ...rest
  }: BrandMarkProps = $props();

  const inner = $derived(renderMarkChildren({ parts, variant, title }));
  const rootStyle = $derived(styleToCssText(buildRootStyle({ colors, color, style })));
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox={markViewBox}
  fill="none"
  width="100%"
  class={className}
  style={rootStyle}
  role={title ? 'img' : undefined}
  aria-label={title || undefined}
  aria-hidden={title ? undefined : true}
  {...rest}
>
  {@html inner}
</svg>
